export enum LeavePolicyStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ApprovalWorkflowStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ApproverType {
  MANAGER = 'MANAGER',
  MANAGERS_MANAGER = 'MANAGERS_MANAGER',
  SPECIFIC_PERSON = 'SPECIFIC_PERSON',
  HR = 'HR',
}

export enum AccrualInterval {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum CutOffType {
  FIXED_DATE = 'FIXED_DATE',
  HIRE_DATE = 'HIRE_DATE',
}

export enum ResetType {
  NONE = 'NONE',
  YEARLY = 'YEARLY',
  POLICY_CUTOFF = 'POLICY_CUTOFF',
}

export enum LeaveTrackingMode {
  AVAILABLE_BALANCE = 'AVAILABLE_BALANCE',
  USAGE_YTD = 'USAGE_YTD',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACTOR = 'CONTRACTOR',
  INTERN = 'INTERN',
}

export enum WorkMode {
  ONSITE = 'ONSITE',
  HYBRID = 'HYBRID',
  REMOTE = 'REMOTE',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum EmployeeRole {
  HR_ADMIN = 'HR_ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum LedgerTransactionType {
  INITIAL_GRANT = 'INITIAL_GRANT',
  ACCRUAL = 'ACCRUAL',
  USAGE = 'USAGE',
  REVERSAL = 'REVERSAL',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  CARRY_OVER = 'CARRY_OVER',
  RESET = 'RESET',
}

export enum LeaveRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  DELETED_BY_HR = 'DELETED_BY_HR',
}

export enum DayPortion {
  FULL_DAY = 'FULL_DAY',
  FIRST_HALF = 'FIRST_HALF',
  SECOND_HALF = 'SECOND_HALF',
}

export enum ApprovalInstanceStatus {
  WAITING = 'WAITING',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
}

export enum AuditActionType {
  WORKFLOW_CREATED = 'WORKFLOW_CREATED',
  WORKFLOW_UPDATED = 'WORKFLOW_UPDATED',
  WORKFLOW_DELETED = 'WORKFLOW_DELETED',
  LEAVE_REQUEST_SUBMITTED = 'LEAVE_REQUEST_SUBMITTED',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED = 'LEAVE_REQUEST_REJECTED',
  LEAVE_REQUEST_CANCELLED = 'LEAVE_REQUEST_CANCELLED',
  LEAVE_REQUEST_DELETED_BY_HR = 'LEAVE_REQUEST_DELETED_BY_HR',
  APPROVAL_STEP_APPROVED = 'APPROVAL_STEP_APPROVED',
  APPROVAL_STEP_REJECTED = 'APPROVAL_STEP_REJECTED',
  APPROVAL_STEP_SKIPPED = 'APPROVAL_STEP_SKIPPED',
  LEDGER_USAGE_CREATED = 'LEDGER_USAGE_CREATED',
  LEDGER_REVERSAL_CREATED = 'LEDGER_REVERSAL_CREATED',
  BALANCE_ADJUSTED = 'BALANCE_ADJUSTED',
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  EMPLOYEE_DELETED = 'EMPLOYEE_DELETED',
  POLICY_ASSIGNED = 'POLICY_ASSIGNED',
}

export enum CalendarScope {
  SELF = 'self',
  TEAM = 'team',
  ALL = 'all',
}
