import { MigrationInterface, QueryRunner } from "typeorm";

export class AddHRReviewFields1784677005679 implements MigrationInterface {
    name = 'AddHRReviewFields1784677005679'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "FK_workflow_steps_workflow"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_country"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_division"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_manager"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_workflow"`);
        await queryRunner.query(`ALTER TABLE "seniority_milestones" DROP CONSTRAINT "FK_milestones_rule"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "FK_leave_rules_policy"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "FK_leave_rules_type"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_leave_policies_country"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_leave_policies_workflow"`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" DROP CONSTRAINT "FK_epa_employee"`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" DROP CONSTRAINT "FK_epa_policy"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_lb_employee"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_lb_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_lb_policy_rule"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_lle_balance"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_lle_employee"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_lle_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_lle_performer"`);
        await queryRunner.query(`ALTER TABLE "public_holidays" DROP CONSTRAINT "FK_public_holidays_country"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" DROP CONSTRAINT "FK_lpd_division"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" DROP CONSTRAINT "FK_lpd_policy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_countries_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_countries_code"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_employees_email_active"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_employees_number_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_manager_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_country_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_division_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_approval_workflow_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_role"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_active_employee_policy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_epa_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_epa_leave_policy_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lb_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lb_leave_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lb_policy_rule_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lb_year"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ledger_idempotency_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_balance_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_leave_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_transaction_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_transaction_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lle_performed_by_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_holiday_nonrecurring"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_holiday_recurring"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lpd_policy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_lpd_division"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "CHK_accrual_consistency"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "CHK_leave_rules_min_request_days"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "CHK_leave_rules_max_request_days"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "CHK_leave_rules_max_consecutive_days"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "CHK_leave_rules_waiting_period_days"`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" DROP CONSTRAINT "CHK_epa_dates"`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "UQ_workflow_step_order"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "UQ_leave_rule_policy_type"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "UQ_employee_leave_type_year"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "leave_type_id" uuid NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "duration_days" numeric(6,2) NOT NULL, "status" "public"."leave_requests_status_enum" NOT NULL DEFAULT 'PENDING', "reason" text, "reviewed_at" TIMESTAMP, "reviewer_id" uuid, "rejection_reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TYPE "public"."approval_workflow_status_enum" RENAME TO "approval_workflow_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_workflows_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" TYPE "public"."approval_workflows_status_enum" USING "status"::"text"::"public"."approval_workflows_status_enum"`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."approval_workflow_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."approver_type_enum" RENAME TO "approver_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_workflow_steps_approver_type_enum" AS ENUM('MANAGER', 'MANAGERS_MANAGER', 'SPECIFIC_PERSON', 'HR')`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ALTER COLUMN "approver_type" TYPE "public"."approval_workflow_steps_approver_type_enum" USING "approver_type"::"text"::"public"."approval_workflow_steps_approver_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approver_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_enum" RENAME TO "employee_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employees_status_enum" USING "status"::"text"::"public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employee_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_type_enum" RENAME TO "employment_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_employment_type_enum" AS ENUM('FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'INTERN')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" TYPE "public"."employees_employment_type_enum" USING "employment_type"::"text"::"public"."employees_employment_type_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" SET DEFAULT 'FULL_TIME'`);
        await queryRunner.query(`DROP TYPE "public"."employment_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."work_mode_enum" RENAME TO "work_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_work_mode_enum" AS ENUM('ONSITE', 'HYBRID', 'REMOTE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" TYPE "public"."employees_work_mode_enum" USING "work_mode"::"text"::"public"."employees_work_mode_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" SET DEFAULT 'ONSITE'`);
        await queryRunner.query(`DROP TYPE "public"."work_mode_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_role_enum" RENAME TO "employee_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_role_enum" AS ENUM('HR_ADMIN', 'MANAGER', 'EMPLOYEE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" TYPE "public"."employees_role_enum" USING "role"::"text"::"public"."employees_role_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" SET DEFAULT 'EMPLOYEE'`);
        await queryRunner.query(`DROP TYPE "public"."employee_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_tracking_mode_enum" RENAME TO "leave_tracking_mode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_types_trackingmode_enum" AS ENUM('AVAILABLE_BALANCE', 'USAGE_YTD')`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "trackingMode" TYPE "public"."leave_types_trackingmode_enum" USING "trackingMode"::"text"::"public"."leave_types_trackingmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_tracking_mode_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."accrual_interval_enum" RENAME TO "accrual_interval_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_rules_accrual_interval_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "accrual_interval" TYPE "public"."leave_rules_accrual_interval_enum" USING "accrual_interval"::"text"::"public"."leave_rules_accrual_interval_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accrual_interval_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."cut_off_type_enum" RENAME TO "cut_off_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_rules_cut_off_type_enum" AS ENUM('FIXED_DATE', 'HIRE_DATE')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" TYPE "public"."leave_rules_cut_off_type_enum" USING "cut_off_type"::"text"::"public"."leave_rules_cut_off_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" SET DEFAULT 'HIRE_DATE'`);
        await queryRunner.query(`DROP TYPE "public"."cut_off_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."reset_type_enum" RENAME TO "reset_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_rules_reset_type_enum" AS ENUM('NONE', 'YEARLY', 'POLICY_CUTOFF')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" TYPE "public"."leave_rules_reset_type_enum" USING "reset_type"::"text"::"public"."leave_rules_reset_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."reset_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "min_request_days" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TYPE "public"."leave_policy_status_enum" RENAME TO "leave_policy_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_policies_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" TYPE "public"."leave_policies_status_enum" USING "status"::"text"::"public"."leave_policies_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."leave_policy_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "available_balance" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "used_ytd" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "pending" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "carried_over" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TYPE "public"."ledger_transaction_type_enum" RENAME TO "ledger_transaction_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_ledger_entries_transaction_type_enum" AS ENUM('INITIAL_GRANT', 'ACCRUAL', 'USAGE', 'REVERSAL', 'MANUAL_ADJUSTMENT', 'CARRY_OVER', 'RESET')`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ALTER COLUMN "transaction_type" TYPE "public"."leave_ledger_entries_transaction_type_enum" USING "transaction_type"::"text"::"public"."leave_ledger_entries_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_transaction_type_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_fa1376321185575cf2226b1491" ON "countries"  ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b47cbb5311bad9c9ae17b8c1ed" ON "countries"  ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_f17dd15aa3970bd4ed5c080fb8" ON "leave_policy_divisions"  ("leave_policy_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7957e495e3c0091cfbcb989e5e" ON "leave_policy_divisions"  ("division_id") `);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "FK_d6d15be28620499e43d1c61c483" FOREIGN KEY ("workflow_id") REFERENCES "approval_workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_7caec81be4bbf6e1d4d345d1ebd" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_d130a915bf54185dd6f7e65df15" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_4ea12c2dd9a94260a678d39304b" FOREIGN KEY ("approval_workflow_id") REFERENCES "approval_workflows"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seniority_milestones" ADD CONSTRAINT "FK_356c8f1faa841372a4f25d608f5" FOREIGN KEY ("leave_rule_id") REFERENCES "leave_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "FK_5ad01cd58ad41830cef7d5b0832" FOREIGN KEY ("policy_id") REFERENCES "leave_policies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "FK_8e45df1e13b52d800f6ac357d3d" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_7b5eb0c5c082fe8504b318bfc63" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_0fca871745ead2553ab13b0b7f6" FOREIGN KEY ("approval_workflow_id") REFERENCES "approval_workflows"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" ADD CONSTRAINT "FK_8d2572ac9f1bfa2cfbb93bb49e2" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" ADD CONSTRAINT "FK_e2ba1a94aa34c30e1e340ce7826" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_2f8aebce74941a2e2168e94ba68" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_d64da0a991d2f4d23d86031530c" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_be3403d8912e88153688814c19a" FOREIGN KEY ("leave_policy_rule_id") REFERENCES "leave_rules"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_1332ac120b5fdd03179c04be0a2" FOREIGN KEY ("balance_id") REFERENCES "leave_balances"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_ca928a318e46a477e9710841b78" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_8b55e659930d8cee554554dfea0" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_9197b5d4fa36a70ca623d7f5d54" FOREIGN KEY ("performed_by_employee_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_54a57db316598806786c2b95323" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_f51357332b63639f1ba6dcb3015" FOREIGN KEY ("reviewer_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public_holidays" ADD CONSTRAINT "FK_a00cf1553664fb20e7b9057aa53" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" ADD CONSTRAINT "FK_f17dd15aa3970bd4ed5c080fb8e" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" ADD CONSTRAINT "FK_7957e495e3c0091cfbcb989e5eb" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" DROP CONSTRAINT "FK_7957e495e3c0091cfbcb989e5eb"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" DROP CONSTRAINT "FK_f17dd15aa3970bd4ed5c080fb8e"`);
        await queryRunner.query(`ALTER TABLE "public_holidays" DROP CONSTRAINT "FK_a00cf1553664fb20e7b9057aa53"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_f51357332b63639f1ba6dcb3015"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_54a57db316598806786c2b95323"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_9197b5d4fa36a70ca623d7f5d54"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_8b55e659930d8cee554554dfea0"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_ca928a318e46a477e9710841b78"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" DROP CONSTRAINT "FK_1332ac120b5fdd03179c04be0a2"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_be3403d8912e88153688814c19a"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_d64da0a991d2f4d23d86031530c"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_2f8aebce74941a2e2168e94ba68"`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" DROP CONSTRAINT "FK_e2ba1a94aa34c30e1e340ce7826"`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" DROP CONSTRAINT "FK_8d2572ac9f1bfa2cfbb93bb49e2"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_0fca871745ead2553ab13b0b7f6"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_7b5eb0c5c082fe8504b318bfc63"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "FK_8e45df1e13b52d800f6ac357d3d"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" DROP CONSTRAINT "FK_5ad01cd58ad41830cef7d5b0832"`);
        await queryRunner.query(`ALTER TABLE "seniority_milestones" DROP CONSTRAINT "FK_356c8f1faa841372a4f25d608f5"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_4ea12c2dd9a94260a678d39304b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_d130a915bf54185dd6f7e65df15"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_7caec81be4bbf6e1d4d345d1ebd"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0"`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "FK_d6d15be28620499e43d1c61c483"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7957e495e3c0091cfbcb989e5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f17dd15aa3970bd4ed5c080fb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b47cbb5311bad9c9ae17b8c1ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa1376321185575cf2226b1491"`);
        await queryRunner.query(`CREATE TYPE "public"."ledger_transaction_type_enum_old" AS ENUM('INITIAL_GRANT', 'ACCRUAL', 'USAGE', 'REVERSAL', 'MANUAL_ADJUSTMENT', 'CARRY_OVER', 'RESET')`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ALTER COLUMN "transaction_type" TYPE "public"."ledger_transaction_type_enum_old" USING "transaction_type"::"text"::"public"."ledger_transaction_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."leave_ledger_entries_transaction_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."ledger_transaction_type_enum_old" RENAME TO "ledger_transaction_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "carried_over" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "pending" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "used_ytd" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ALTER COLUMN "available_balance" SET DEFAULT 0.00`);
        await queryRunner.query(`CREATE TYPE "public"."leave_policy_status_enum_old" AS ENUM('DRAFT', 'ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" TYPE "public"."leave_policy_status_enum_old" USING "status"::"text"::"public"."leave_policy_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."leave_policies_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_policy_status_enum_old" RENAME TO "leave_policy_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "min_request_days" SET DEFAULT 0.5`);
        await queryRunner.query(`CREATE TYPE "public"."reset_type_enum_old" AS ENUM('NONE', 'YEARLY', 'POLICY_CUTOFF')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" TYPE "public"."reset_type_enum_old" USING "reset_type"::"text"::"public"."reset_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "reset_type" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."leave_rules_reset_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reset_type_enum_old" RENAME TO "reset_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."cut_off_type_enum_old" AS ENUM('FIXED_DATE', 'HIRE_DATE')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" TYPE "public"."cut_off_type_enum_old" USING "cut_off_type"::"text"::"public"."cut_off_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "cut_off_type" SET DEFAULT 'HIRE_DATE'`);
        await queryRunner.query(`DROP TYPE "public"."leave_rules_cut_off_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cut_off_type_enum_old" RENAME TO "cut_off_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."accrual_interval_enum_old" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ALTER COLUMN "accrual_interval" TYPE "public"."accrual_interval_enum_old" USING "accrual_interval"::"text"::"public"."accrual_interval_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."leave_rules_accrual_interval_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."accrual_interval_enum_old" RENAME TO "accrual_interval_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_tracking_mode_enum_old" AS ENUM('AVAILABLE_BALANCE', 'USAGE_YTD')`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "trackingMode" TYPE "public"."leave_tracking_mode_enum_old" USING "trackingMode"::"text"::"public"."leave_tracking_mode_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."leave_types_trackingmode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_tracking_mode_enum_old" RENAME TO "leave_tracking_mode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_role_enum_old" AS ENUM('HR_ADMIN', 'MANAGER', 'EMPLOYEE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" TYPE "public"."employee_role_enum_old" USING "role"::"text"::"public"."employee_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "role" SET DEFAULT 'EMPLOYEE'`);
        await queryRunner.query(`DROP TYPE "public"."employees_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_role_enum_old" RENAME TO "employee_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."work_mode_enum_old" AS ENUM('ONSITE', 'HYBRID', 'REMOTE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" TYPE "public"."work_mode_enum_old" USING "work_mode"::"text"::"public"."work_mode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "work_mode" SET DEFAULT 'ONSITE'`);
        await queryRunner.query(`DROP TYPE "public"."employees_work_mode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."work_mode_enum_old" RENAME TO "work_mode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_type_enum_old" AS ENUM('FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'INTERN')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" TYPE "public"."employment_type_enum_old" USING "employment_type"::"text"::"public"."employment_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" SET DEFAULT 'FULL_TIME'`);
        await queryRunner.query(`DROP TYPE "public"."employees_employment_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_type_enum_old" RENAME TO "employment_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employee_status_enum_old" USING "status"::"text"::"public"."employee_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_enum_old" RENAME TO "employee_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."approver_type_enum_old" AS ENUM('MANAGER', 'MANAGERS_MANAGER', 'SPECIFIC_PERSON', 'HR')`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ALTER COLUMN "approver_type" TYPE "public"."approver_type_enum_old" USING "approver_type"::"text"::"public"."approver_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."approval_workflow_steps_approver_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approver_type_enum_old" RENAME TO "approver_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_workflow_status_enum_old" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" TYPE "public"."approval_workflow_status_enum_old" USING "status"::"text"::"public"."approval_workflow_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."approval_workflows_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_workflow_status_enum_old" RENAME TO "approval_workflow_status_enum"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "UQ_employee_leave_type_year" UNIQUE ("employee_id", "leave_type_id", "year")`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "UQ_leave_rule_policy_type" UNIQUE ("policy_id", "leave_type_id")`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "UQ_workflow_step_order" UNIQUE ("workflow_id", "step_order")`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" ADD CONSTRAINT "CHK_epa_dates" CHECK (((effective_to IS NULL) OR (effective_to > effective_from)))`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "CHK_leave_rules_waiting_period_days" CHECK ((waiting_period_days >= 0))`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "CHK_leave_rules_max_consecutive_days" CHECK (((max_consecutive_days IS NULL) OR (max_consecutive_days > (0)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "CHK_leave_rules_max_request_days" CHECK (((max_request_days IS NULL) OR (max_request_days >= min_request_days)))`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "CHK_leave_rules_min_request_days" CHECK ((min_request_days > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "CHK_accrual_consistency" CHECK ((((is_accrued = true) AND (accrual_interval IS NOT NULL) AND (accrual_rate IS NOT NULL) AND (accrual_rate > (0)::numeric)) OR ((is_accrued = false) AND (accrual_interval IS NULL) AND (accrual_rate IS NULL))))`);
        await queryRunner.query(`CREATE INDEX "IDX_lpd_division" ON "leave_policy_divisions" USING btree ("division_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lpd_policy" ON "leave_policy_divisions" USING btree ("leave_policy_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_holiday_recurring" ON "public_holidays" USING btree ("country_id") WHERE (is_recurring = true)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_holiday_nonrecurring" ON "public_holidays" USING btree ("country_id", "date") WHERE (is_recurring = false)`);
        await queryRunner.query(`CREATE INDEX "IDX_lle_performed_by_employee_id" ON "leave_ledger_entries" USING btree ("performed_by_employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lle_transaction_date" ON "leave_ledger_entries" USING btree ("transaction_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_lle_transaction_type" ON "leave_ledger_entries" USING btree ("transaction_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_lle_leave_type_id" ON "leave_ledger_entries" USING btree ("leave_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lle_employee_id" ON "leave_ledger_entries" USING btree ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lle_balance_id" ON "leave_ledger_entries" USING btree ("balance_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ledger_idempotency_key" ON "leave_ledger_entries" USING btree ("idempotency_key") WHERE (idempotency_key IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_lb_year" ON "leave_balances" USING btree ("year") `);
        await queryRunner.query(`CREATE INDEX "IDX_lb_policy_rule_id" ON "leave_balances" USING btree ("leave_policy_rule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lb_leave_type_id" ON "leave_balances" USING btree ("leave_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_lb_employee_id" ON "leave_balances" USING btree ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_epa_leave_policy_id" ON "employee_policy_assignments" USING btree ("leave_policy_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_epa_employee_id" ON "employee_policy_assignments" USING btree ("employee_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_active_employee_policy" ON "employee_policy_assignments" USING btree ("employee_id") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "IDX_employees_role" ON "employees" USING btree ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_status" ON "employees" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_approval_workflow_id" ON "employees" USING btree ("approval_workflow_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_division_id" ON "employees" USING btree ("division_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_country_id" ON "employees" USING btree ("country_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_manager_id" ON "employees" USING btree ("manager_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_employees_number_active" ON "employees" USING btree ("employee_number") WHERE ((employee_number IS NOT NULL) AND ("deletedAt" IS NULL))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_employees_email_active" ON "employees" USING btree ("email") WHERE ("deletedAt" IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_countries_code" ON "countries" USING btree ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_countries_name" ON "countries" USING btree ("name") `);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" ADD CONSTRAINT "FK_lpd_policy" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_divisions" ADD CONSTRAINT "FK_lpd_division" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public_holidays" ADD CONSTRAINT "FK_public_holidays_country" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_lle_performer" FOREIGN KEY ("performed_by_employee_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_lle_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_lle_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger_entries" ADD CONSTRAINT "FK_lle_balance" FOREIGN KEY ("balance_id") REFERENCES "leave_balances"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_lb_policy_rule" FOREIGN KEY ("leave_policy_rule_id") REFERENCES "leave_rules"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_lb_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_lb_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" ADD CONSTRAINT "FK_epa_policy" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_policy_assignments" ADD CONSTRAINT "FK_epa_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_leave_policies_workflow" FOREIGN KEY ("approval_workflow_id") REFERENCES "approval_workflows"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_leave_policies_country" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "FK_leave_rules_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_rules" ADD CONSTRAINT "FK_leave_rules_policy" FOREIGN KEY ("policy_id") REFERENCES "leave_policies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seniority_milestones" ADD CONSTRAINT "FK_milestones_rule" FOREIGN KEY ("leave_rule_id") REFERENCES "leave_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_workflow" FOREIGN KEY ("approval_workflow_id") REFERENCES "approval_workflows"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_manager" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_division" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_country" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "FK_workflow_steps_workflow" FOREIGN KEY ("workflow_id") REFERENCES "approval_workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
